services:
  - type: worker
    name: football-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: "YOUR_TELEGRAM_BOT_TOKEN"
