services:
  - type: web
    name: football-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: "8237073959:AAGoZT6Th4nhLF2t_QgXmqnRMqvKQgMYS70"
